### ISSUE TITLE
加入明月拼音中失败

### ISSUE THREAD

**Issue by chzhsh** [shewer/rime-english#2]
请问按说明结构设置了,加入明月拼音中没有效果,不知哪里出错,能提供打包好的吗？

**Comment by shewer** [comment]
我測試沒問題
在中文模式下  {F10} english  on/off
 weasel 請按 F9 展開分行 ，字典字串太長會造成 rime 重啟

my userdir =  Users\shewe\AppData\Roaming\Rime
git  clone    git  tools ...     lua/tools
git clone  https://git..../lua-english  lua/english
cp lua/english/english_plugin.yaml .

* --- add  2 line in rime.lua
```lua
load_module=require('tools/loadmodule')
load_module.load('english','english',"english_tw.txt")
-----
```
*  add  1line  in  patch:  luna_pinyin.custom.yaml 
```yaml 
patch:
    __include: engilsh_plug:/patch
```


* redeploy 
* check   build/luna_pinyin.schema.yaml/
```yaml
engine:
  filters:
    - "reverse_lookup_filter@cangjie_lookup"
    - "simplifier@zh_simp"
    - "simplifier@zh_tw"
    - uniquifier
    - "lua_filter@english_filter"  # <-------
  processors:
    - "lua_processor@english_processor"  # <-- 
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - "lua_segmentor@english_segmentor"   # <-----
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - "affix_segmentor@alphabet"
    - "affix_segmentor@cangjie"
    - "affix_segmentor@pinyin"
    - punct_segmentor
    - fallback_segmentor
  translators:
    - "lua_translator@english_translator"  # <---   
    - punct_translator
    - reverse_lookup_translator
    - script_translator
```
